### YamlMime:PythonEnum
uid: azure.mgmt.keyvault.v2019_09_01.models.Reason
name: Reason
fullName: azure.mgmt.keyvault.v2019_09_01.models.Reason
summary: 'The reason that a vault name could not be used. The Reason element is only
  returned if

  NameAvailable is false.'
module: azure.mgmt.keyvault.v2019_09_01.models
inheritances:
- builtins.str
- enum.Enum
fields:
- name: account_name_invalid
  uid: azure.mgmt.keyvault.v2019_09_01.models.Reason.account_name_invalid
- name: already_exists
  uid: azure.mgmt.keyvault.v2019_09_01.models.Reason.already_exists
