### YamlMime:PythonClass
uid: azure.cognitiveservices.knowledge.qnamaker.models.error_response_error_py3.ErrorResponseError
name: ErrorResponseError
fullName: azure.cognitiveservices.knowledge.qnamaker.models.error_response_error_py3.ErrorResponseError
module: azure.cognitiveservices.knowledge.qnamaker.models.error_response_error_py3
inheritances:
- azure.cognitiveservices.knowledge.qnamaker.models.error_py3.Error
summary: 'The error object.


  All required parameters must be populated in order to send to Azure.'
constructor:
  syntax: 'ErrorResponseError(*, code, message: Optional[str] = None, target: Optional[str]
    = None, details=None, inner_error=None, **kwargs) -> None'
  parameters:
  - name: code
    description: 'Required. One of a server-defined set of error codes.

      Possible values include: ''BadArgument'', ''Forbidden'', ''NotFound'',

      ''KbNotFound'', ''Unauthorized'', ''Unspecified'', ''EndpointKeysError'',

      ''QuotaExceeded'', ''QnaRuntimeError'', ''SKULimitExceeded'',

      ''OperationNotFound'', ''ServiceError'', ''ValidationFailure'',

      ''ExtractionFailure'''
    types:
    - '[str](https://docs.python.org/3.6/library/stdtypes.html#str'
  - name: message
    description: A human-readable representation of the error.
    types:
    - '[str](https://docs.python.org/3.6/library/stdtypes.html#str)'
  - name: target
    description: The target of the error.
    types:
    - '[str](https://docs.python.org/3.6/library/stdtypes.html#str)'
  - name: details
    description: 'An array of details about specific errors that led to this

      reported error.'
    types:
    - '[list](https://docs.python.org/3.6/library/stdtypes.html#list)[<xref:azure.cognitiveservices.knowledge.qnamaker.models.Error>]'
  - name: inner_error
    description: 'An object containing more specific information than

      the current object about the error.'
    types:
    - <xref:azure.cognitiveservices.knowledge.qnamaker.models.InnerErrorModel>
