### YamlMime:PythonClass
uid: azure.mgmt.datamigration.models.ValidateMigrationInputSqlServerSqlMITaskOutput
name: ValidateMigrationInputSqlServerSqlMITaskOutput
fullName: azure.mgmt.datamigration.models.ValidateMigrationInputSqlServerSqlMITaskOutput
module: azure.mgmt.datamigration.models
inheritances:
- msrest.serialization.Model
summary: 'Output for task that validates migration input for SQL to Azure SQL Managed
  Instance migrations.


  Variables are only populated by the server, and will be ignored when sending a request.'
constructor:
  syntax: 'ValidateMigrationInputSqlServerSqlMITaskOutput(*, database_backup_info:
    Optional[azure.mgmt.datamigration.models._models_py3.DatabaseBackupInfo] = None,
    **kwargs)'
  parameters:
  - name: database_backup_info
    description: Information about backup files when existing backup mode is used.
    types:
    - <xref:azure.mgmt.datamigration.models.DatabaseBackupInfo>
variables:
- description: Result identifier.
  name: id
  types:
  - https://docs.python.org/3.6/library/functions.html#id) ([str](https://docs.python.org/3.6/library/stdtypes.html#str)
- description: Name of database.
  name: id
  types:
  - '[str](https://docs.python.org/3.6/library/stdtypes.html#str)'
- description: Errors associated with the RestoreDatabaseName.
  name: id
  types:
  - '[list](https://docs.python.org/3.6/library/stdtypes.html#list)[<xref:azure.mgmt.datamigration.models.ReportableException>]'
- description: Errors associated with the BackupFolder path.
  name: id
  types:
  - '[list](https://docs.python.org/3.6/library/stdtypes.html#list)[<xref:azure.mgmt.datamigration.models.ReportableException>]'
- description: 'Errors associated with backup share user name and

    password credentials.'
  name: id
  types:
  - '[list](https://docs.python.org/3.6/library/stdtypes.html#list)[<xref:azure.mgmt.datamigration.models.ReportableException>]'
- description: Errors associated with the storage account provided.
  name: id
  types:
  - '[list](https://docs.python.org/3.6/library/stdtypes.html#list)[<xref:azure.mgmt.datamigration.models.ReportableException>]'
- description: Errors associated with existing backup files.
  name: id
  types:
  - '[list](https://docs.python.org/3.6/library/stdtypes.html#list)[<xref:azure.mgmt.datamigration.models.ReportableException>]'
